[inbound]
watch_dir = "testData"

[device]
add_public_ip = false
public_ip_tag_key = "public_ip"

[[sinks]]
name = "local_json_archive"
type = "file"
config.output_path = "/data/archive/json-data"
config.format = "jsonl" 
config.rotation = 'daily'

[[sinks]]
name = "local_csv_archive"
type = "file"
config.output_path = "/data/archive/csv-data"
config.format = "csv" 
config.startup = true
config.max_size_mb = 10

[[sinks]]
name = "mqtt_daemon"
type = "mqtt"

config.broker = "localhost"
config.port = 1883
[config.measurement_map]
    "temperature" = "daq/sensors/temp"
    "pressure" = "daq/sensors/pressure"
fallback_topic = "daq/unknown"
format = "line_protocol"
qos = 1
